CREATE DATABASE IF NOT EXISTS CORE_DEV;
CREATE DATABASE IF NOT EXISTS TICKET_DEV;
CREATE DATABASE IF NOT EXISTS JOURNAL_DEV;

CREATE USER IF NOT EXISTS 'CORE'@'%' IDENTIFIED BY 'CORE_123';
GRANT SELECT, INSERT, UPDATE, DELETE ON CORE_DEV.* TO 'CORE'@'%';

CREATE USER IF NOT EXISTS 'TICKET'@'%' IDENTIFIED BY 'TICKET_123';
GRANT SELECT, INSERT, UPDATE, DELETE ON TICKET_DEV.* TO 'TICKET'@'%';

CREATE USER IF NOT EXISTS 'JOURNAL'@'%' IDENTIFIED BY 'JOURNAL_123';
GRANT SELECT, INSERT ON JOURNAL_DEV.* TO 'JOURNAL'@'%';

CREATE USER IF NOT EXISTS 'DB_ADMIN'@'%' IDENTIFIED BY 'DB_ADMIN_123';
GRANT ALL PRIVILEGES ON CORE_DEV.* TO 'DB_ADMIN'@'%';
GRANT ALL PRIVILEGES ON TICKET_DEV.* TO 'DB_ADMIN'@'%';
GRANT ALL PRIVILEGES ON JOURNAL_DEV.* TO 'DB_ADMIN'@'%';