CREATE DATABASE IF NOT EXISTS CORE_DEV;
CREATE DATABASE IF NOT EXISTS TICKET_DEV;
CREATE DATABASE IF NOT EXISTS JOURNAL_DEV;
CREATE DATABASE IF NOT EXISTS PARTNER;


ALTER DATABASE CORE_DEV CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER DATABASE TICKET_DEV CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER DATABASE JOURNAL_DEV CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER DATABASE PARTNER CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

SET NAMES utf8;

CREATE USER IF NOT EXISTS 'CORE'@'%' IDENTIFIED BY 'CORE_123';
GRANT SELECT, INSERT, UPDATE, DELETE ON CORE_DEV.* TO 'CORE'@'%';

CREATE USER IF NOT EXISTS 'TICKET'@'%' IDENTIFIED BY 'TICKET_123';
GRANT SELECT, INSERT, UPDATE, DELETE ON TICKET_DEV.* TO 'TICKET'@'%';

CREATE USER IF NOT EXISTS 'JOURNAL'@'%' IDENTIFIED BY 'JOURNAL_123';
GRANT SELECT, INSERT ON JOURNAL_DEV.* TO 'JOURNAL'@'%';

CREATE USER IF NOT EXISTS 'PARTNER'@'%' IDENTIFIED BY 'PARTNER_123';
GRANT SELECT, INSERT, UPDATE ON PARTNER.* TO 'PARTNER'@'%';

GRANT ALL PRIVILEGES ON CORE_DEV.* TO 'DB_ADMIN'@'%';
GRANT ALL PRIVILEGES ON TICKET_DEV.* TO 'DB_ADMIN'@'%';
GRANT ALL PRIVILEGES ON JOURNAL_DEV.* TO 'DB_ADMIN'@'%';
GRANT ALL PRIVILEGES ON PARTNER.* TO 'DB_ADMIN'@'%';

-- Initializes partner schema
source /etc/db_scripts/partner_db.sql;

-- Initializes core-api schema
source /etc/db_scripts/core_db.sql;

-- Initializes ticket-api schema
source /etc/db_scripts/ticket_db.sql;

-- Initializes journal-consumer schema
source /etc/db_scripts/journal_db.sql;