USE JOURNAL_DEV;


CREATE TABLE JOURNAL
(
    ID          INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
    USER        VARCHAR(255),
    APPLICATION VARCHAR(255),
    TIMESTAMP   TIMESTAMP,
    TYPE        VARCHAR(255),
    CONTENT     MEDIUMTEXT
);