server:
  port: 8082

spring:
  application:
    name: MAIN-API
  rabbitmq:
    host: ${MQ_HOST:localhost}
    username: ${MQ_USERNAME:api_service}
    password: ${MQ_PASSWORD:api_service_123}
    stream:
      routing-key: ${MQ_ROUTING_KEY:JOURNAL}
      topic-key: ${MQ_TOPIC_KEY:CENTRAL}


springdoc:
  swagger-ui:
    display-operation-id: true
    syntax-highlight:
      activated: true
      theme: "agate"

core-api:
  url: '${CORE_API_URL:http://localhost:8081/}'

ticket-api:
  url: '${CORE_API_URL:http://localhost:8083/}'