server:
  port: 8082

spring:
  application:
    name: MAIN-API


springdoc:
  swagger-ui:
    display-operation-id: true
    syntax-highlight:
      activated: true
      theme: "agate"

core-api:
  url: '${CORE_API_URL:http://localhost:8081/}'

ticket-api:
  url: '${CORE_API_URL:http://localhost:8083/}'