version: '3.3'

services:

  # MySQL
  database:
    build:
      context: database
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database:/etc/db_scripts
    env_file:
      - .env
    environment:
      - TZ=Europe/Budapest
    container_name: ts_dev_database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s

  # RabbitMQ
#  message_queue:
#    image: rabbitmq:3.12.10-management-alpine
#    container_name: ts_rabbit
#    volumes:
#      - ./rabbit_mq/rabbit.conf:/etc/rabbitmq/rabbitmq.conf
#      - ./rabbit_mq/definitions.json:/etc/rabbitmq/definitions.json
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 5s
#        max_attempts: 5
#        window: 60s